# Generated by Django 3.2.18 on 2023-05-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20230501_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='op3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
